### ISSUE TITLE
Starship prompt

### ISSUE THREAD

**Issue by andreicorpo** [marlonrichert/zsh-snap#77] opened 2021-06-02 16:54 UTC
Hi, i get this error when using the starship prompt:
```
.znap.prompt.precmd:6: command not found: add-zle-hook-widget
```
This is how I init it:
```
    znap eval starship "starship init zsh --print-full-init"
    znap prompt
```

Also my cursor seems to be invisible.

**Comment by marlonrichert** [comment] 2021-06-03 16:21
> ```zsh
> .znap.prompt.precmd:6: command not found: add-zle-hook-widget
> ```

That's fixed now.

**Comment by marlonrichert** [comment] 2021-06-03 16:23
> Also my cursor seems to be invisible.

And that is apparently fixed now, too. 🙂

**Closed by marlonrichert** 2021-06-03 16:23 UTC
Labels: bug

**Comment by andreicorpo** [comment] 2021-06-03 17:51
My cursor still seems to be invisible.
The only other plugin used is `zsh-users/zsh-syntax-highlighting`

**Comment by andreicorpo** [comment] 2021-06-03 17:56
These plugins also seem to make the cursor invisible:
```
znap source zsh-users/zsh-autosuggestions
znap source zsh-users/zsh-completions
```

**Comment by marlonrichert** [comment] 2021-06-03 20:20
I cannot reproduce that. Here's what I did:

<details><summary>(click to expand)</summary>

```zsh 
% cd $(mktemp -d)
% print "PS1='%# ' PS2='' RPS2='< %^'\nsetopt transientrprompt" > .zshrc
% exec env -i HOME=$PWD TERM=$TERM zsh -d 
% print '
znap eval starship/starship "starship init zsh --print-full-init"
znap prompt
znap source zsh-users/zsh-completions
znap source zsh-users/zsh-autosuggestions
znap source zsh-users/zsh-syntax-highlighting
' >> .zshrc
% git clone --depth 1 -- https://github.com/marlonrichert/zsh-snap.git
Cloning into 'zsh-snap'...
remote: Enumerating objects: 42, done.
remote: Counting objects: 100% (42/42), done.
remote: Compressing objects: 100% (39/39), done.
remote: Total 42 (delta 0), reused 10 (delta 0), pack-reused 0
Receiving objects: 100% (42/42), 18.35 KiB | 213.00 KiB/s, done.
% source zsh-snap/install.zsh

Configuring Znap...

Where do you (want to) keep your repos and/or plugins?
> ~/Git
No such dir ~/Git. Create? [yn] y
Move Znapʼs own repo to ~/Git, too? [yn] y

Updating ~/.zshrc...
Installation complete.

Validating dotfiles...
Restarting Zsh...
Cloning into 'starship'...
remote: Enumerating objects: 460, done.
remote: Counting objects: 100% (460/460), done.
remote: Compressing objects: 100% (268/268), done.
remote: Total 460 (delta 148), reused 259 (delta 89), pack-reused 0
Receiving objects: 100% (460/460), 5.32 MiB | 5.37 MiB/s, done.
Resolving deltas: 100% (148/148), done.

~ 
❯ Cloning into 'zsh-completions'...
remote: Enumerating objects: 156, done.
remote: Counting objects: 100% (156/156), done.
remote: Compressing objects: 100% (151/151), done.
remote: Total 156 (delta 47), reused 38 (delta 3), pack-reused 0
Receiving objects: 100% (156/156), 346.19 KiB | 1.07 MiB/s, done.
Resolving deltas: 100% (47/47), done.
Cloning into 'zsh-autosuggestions'...
remote: Enumerating objects: 73, done.
remote: Counting objects: 100% (73/73), done.
remote: Compressing objects: 100% (64/64), done.
remote: Total 73 (delta 9), reused 32 (delta 3), pack-reused 0
Receiving objects: 100% (73/73), 35.13 KiB | 378.00 KiB/s, done.
Resolving deltas: 100% (9/9), done.
Cloning into 'zsh-syntax-highlighting'...
remote: Enumerating objects: 366, done.

~ took 5s 
❯ znap restart
Validating dotfiles...
Restarting Zsh...

~ 

~ 
❯

```
</details>

After this, the cursor is blinking and visible.

**Comment by anthonycicc** [comment] 2021-07-06 15:10
I encountered this issue as well - I had disabled .zwc compilation, which meant that [`autoload -Uz add-zle-hook-widget` from .znap.compile](https://github.com/marlonrichert/zsh-snap/blob/b5a747d4ced2c0a22b6a095be6b88318aab6e5bb/functions/.znap.compile#L5) wasn't getting sourced in.

I patched my copy of the repository to add the autoload to `.znap.prompt`, and can make a PR (if it would get accepted by  @marlonrichert)

**Comment by marlonrichert** [comment] 2021-07-14 09:54
Fixed.
