### ISSUE TITLE
Error with latest Starship prompt

### ISSUE THREAD

**Issue by tshu-w** [marlonrichert/zsh-snap#163] opened 2022-01-17 06:59 UTC
Hi, I got 
```
error: Invalid value for '--jobs <JOBS>': cannot parse integer from empty string

For more information try --help
```
with the latest startship
```
znap eval starship 'starship init zsh --print-full-init'
znap prompt
```

comment out `znap prompt` works fine.

zsh 5.8 (x86_64-apple-darwin21.0)
starship stable 1.2.1
znap e019e00

**Comment by mgoodness** [comment] 2022-01-21 00:01
Attached is the output from `starship init zsh --print-full-init`, in case it helps.

Note line 11: `zmodload zsh/parameter  # Needed to access jobstates variable for STARSHIP_JOBS_COUNT`. Could there be a conflict between that and https://github.com/marlonrichert/zsh-snap/commit/e019e0034698ed53b00ee5ed0d4a354fe864dcb0?

[starship.txt](https://github.com/marlonrichert/zsh-snap/files/7909228/starship.txt)

**Comment by marlonrichert** [comment] 2022-01-21 07:22
> Note line 11: `zmodload zsh/parameter  # Needed to access jobstates variable for STARSHIP_JOBS_COUNT`. Could there be a conflict between that and https://github.com/marlonrichert/zsh-snap/commit/e019e0034698ed53b00ee5ed0d4a354fe864dcb0?

No, that's completely unrelated.

The problem is that `znap prompt` tries to [`print -nPr -- "$PS1"`](https://github.com/marlonrichert/zsh-snap/blob/e019e0034698ed53b00ee5ed0d4a354fe864dcb0/functions/.znap.prompt#L54), but this fails due to some of the variables in Starship's new `$PS1` not having been set yet at this point. We are probably missing the execution of a `precmd` hook.

**Comment by marlonrichert** [comment] 2022-01-21 07:31
Yep, I can confirm that this fixes the problem:
```
znap eval starship 'starship init zsh --print-full-init'
starship_precmd
znap prompt
```

**Comment by marlonrichert** [comment] 2022-01-21 09:14
[This pull request to Starship](https://github.com/starship/starship/pull/3480), once merged, will make it possible to simplify the above to
```zsh
znap eval starship 'starship init zsh --print-full-init'
znap prompt starship
```

**Comment by mgoodness** [comment] 2022-01-21 15:04
Thanks much! Have added `starship_precmd` to my config and will keep an eye on the PR.

**Comment by marlonrichert** [comment] 2022-02-09 06:10
@tshu-w @mgoodness My pull request to Starship has been merged.

**Comment by billyogat** [comment] 2022-02-10 03:39
Is this expected to be fixed with starship v1.3.0?

I'm still seeing this issue.

```
❯ starship -V
starship 1.3.0

❯ znap restart
Validating dotfiles...
Restarting Zsh...
error: Invalid value for '--jobs <JOBS>': cannot parse integer from empty string

For more information try --help

NOTE:
    passed arguments: ["prompt", "--terminal-width=127", "--keymap=", "--status=", "--pipestatus=", "--cmd-duration=", "--jobs="]
```

**Comment by marlonrichert** [comment] 2022-02-10 08:16
You're right. It requires one more change from my end.

**Comment by dannysteenman** [comment] 2022-02-14 07:49
> [This pull request to Starship](https://github.com/starship/starship/pull/3480), once merged, will make it possible to simplify the above to
> 
> ```shell
> znap eval starship 'starship init zsh --print-full-init'
> znap prompt starship
> ```

Hi, I get the same error as @billyogat when I use the commands above. However, if I change it to this:
```
znap eval starship 'starship init zsh --print-full-init'
prompt_starship_precmd
znap prompt
```

Then it works.

**Comment by billyogat** [comment] 2022-02-22 15:37
> > [This pull request to Starship](https://github.com/starship/starship/pull/3480), once merged, will make it possible to simplify the above to
> > ```shell
> > znap eval starship 'starship init zsh --print-full-init'
> > znap prompt starship
> > ```
> 
> Hi, I get the same error as @billyogat when I use the commands above. However, if I change it to this:
> 
> ```
> znap eval starship 'starship init zsh --print-full-init'
> prompt_starship_precmd
> znap prompt
> ```
> 
> Then it works.

This works for me as well.

**Closed** 2022-02-22 15:57 UTC
Labels: enhancement

**Comment by marlonrichert** [comment] 2022-02-22 16:02
@theol0403 @Jaakkonen @muuvmuuv @tshu-w @dannysteenman @billyogat Starting with aa8396a5354943709468ca634eb32e170a79d293, the following should now work:
```zsh
znap eval starship 'starship init zsh --print-full-init'
znap prompt starship
```

---

@mgoodness Thanks for the sponsorship! 😻

**Comment by mgoodness** [comment] 2022-02-23 18:22
Looks good here. Thank you!

**Comment by mgoodness** [comment] 2022-02-23 19:14
@marlonrichert I spoke too soon. Using https://github.com/marlonrichert/zsh-snap/commit/aa8396a5354943709468ca634eb32e170a79d293, I'm getting extraneous information in the git portion of my Starship prompt. In the screenshot below, I only expect the down arrow in the red brackets - I don't know where the `2815` sequence comes from.

![Screen Shot 2022-02-23 at 12 49 28 PM](https://user-images.githubusercontent.com/2781657/155387654-cd0ba659-564a-4bd5-835b-60e305fcd1d7.png)

Seems to be tied into command history, though, as the sequence increments as I run new commands. Reverting to the previous zsh-snap commit and config corrects the behavior.

![Screen Shot 2022-02-23 at 1 13 58 PM](https://user-images.githubusercontent.com/2781657/155390994-8de4e0ff-a9bf-4870-a079-97c473049d79.png)



LMK if you'd rather this be its own issue.

**Comment by muuvmuuv** [comment] 2022-02-23 21:28
@mgoodness this seems strange. Have you tried `znap clean`? I know that znap hooks into some git stuff to make it faster maybe just a caching issue. I also had to remove the znap cache in `$XDG_CACHE_HOME/zsh-snap/eval`. Maybe this helps.

**Comment by mgoodness** [comment] 2022-02-23 23:42
@muuvmuuv No luck with either `znap clean` or a manual cleanup of `$XDG_CACHE_HOME/zsh-snap/eval`. I can use https://github.com/marlonrichert/zsh-snap/commit/aa8396a5354943709468ca634eb32e170a79d293 with config

```shell
znap eval starship 'starship init zsh --print-full-init'
prompt_starship_precmd
znap prompt
```

But as soon as I replace the last two lines with `znap prompt starship` and reload, I get the weird behavior.

**Comment by tshu-w** [comment] 2022-02-24 00:23
Yes, I'm facing the same issue with 
```
znap eval starship 'starship init zsh --print-full-init'
znap prompt starship
```
<img width="274" alt="Screen Shot 2022-02-24 at 08 23 14" src="https://user-images.githubusercontent.com/13161779/155433412-cfa19c51-7c36-40b0-868c-31a908ae55b8.png">

**Comment by marlonrichert** [comment] 2022-02-24 08:03
> LMK if you'd rather this be its own issue.

@mgoodness @tshu-w Yes, please open a new issue for this.

**Comment by tshu-w** [comment] 2022-02-24 08:18
@marlonrichert Hi, I open at https://github.com/marlonrichert/zsh-snap/issues/165, let me know if you need more info.

**Comment by muuvmuuv** [comment] 2022-02-25 09:07
@mgoodness yes I had experienced the same but after updating, patching the init script _and then_ delete the cache as I described, it worked.
