### ISSUE TITLE
`znap restart` fails with no error message when using `znap fpath`

### ISSUE THREAD

**Issue by optix2000** [marlonrichert/zsh-snap#149] opened 2021-12-12 05:56 UTC
When using `znap fpath _kubectl 'kubectl completion zsh'`, `znap restart` will throw the following error:
```
% znap restart
Validating dotfiles...
Validation failed with exit status 1.
Restart aborted.
```

1. There doesn't appear to be any problem with `znap fpath`. Restarting zsh (`exec zsh`) loads fine without any errors and the `kubectl` completion works as expected.
2. There's no error message explaining what line failed when running `znap restart`. If the user has a large .zshrc, it could take a long time to find the offending line.

Complete .zshrc:
```zsh
# Set homebrew path
if [[ "$OSTYPE" == "darwin"* ]]; then
  eval $(/opt/homebrew/bin/brew shellenv)
fi

source ~/.zsh/zsh-snap/znap.zsh

znap fpath _kubectl 'kubectl completion zsh'
```

Removing `znap fpath` will allow `znap restart` to run without errors.

**Comment by marlonrichert** [comment] 2021-12-12 10:19
I'm unable to reproduce this:
```zsh
% cd $(mktemp -d)
mkdir -p Git
git -C Git clone --depth 1 -- https://github.com/marlonrichert/zsh-snap.git
> .zshrc <<EOF
PS1='%# '
eval \$(brew shellenv)
source ~/Git/zsh-snap/znap.zsh
znap fpath _kubectl 'kubectl completion zsh'
EOF
env -i HOME=$PWD PATH=$PATH TERM=$TERM zsh -d

/private/var/folders/8v/16q0d4s92tv7wrwxhjz6hktc0000gn/T/tmp.bsju1VjL/
Cloning into 'zsh-snap'...
remote: Enumerating objects: 46, done.
remote: Counting objects: 100% (46/46), done.
remote: Compressing objects: 100% (44/44), done.
remote: Total 46 (delta 0), reused 11 (delta 0), pack-reused 0
Receiving objects: 100% (46/46), 22.44 KiB | 717.00 KiB/s, done.
% znap restart
Validating dotfiles...
Restarting Zsh...
%
```
Perhaps there is something else in your environment that's messing things up?

If you do `print $ZSH_VERSION`, what version does it say?

**Comment by marlonrichert** [comment] 2021-12-18 21:26
@optix2000 ?

**Comment by marlonrichert** [comment] 2021-12-24 18:32
Closing, as I haven’t heard back from @optix2000.

**Comment by optix2000** [comment] 2022-01-01 01:11
Sorry for the delay, I threw this out right before I went out on vacation.
```
# print $ZSH_VERSION
5.8
```

I dug a bit deeper. I can't repro this on a freshly launched shell, but I can repro this in an existing shell.

The following steps work for me:

1. Start zsh with above config.
2. Add any `znap source` line _before_ `znap fpath`. In my case I used `znap source ohmyzsh/ohmyzsh plugins/gnu-utils`
Config should look something like this now:
```
eval $(/opt/homebrew/bin/brew shellenv)
source ~/.zsh/zsh-snap/znap.zsh
znap source ohmyzsh/ohmyzsh plugins/gnu-utils
znap fpath _kubectl 'kubectl completion zsh'
```
3. Run `znap restart`

**Comment by marlonrichert** [comment] 2022-01-03 14:42
I'm unable to reproduce this:
```zsh
% $(mktemp -d)
> .zshrc <<EOF
PS1='%# ' PS2= RPS2='< %^'; setopt transientrprompt
eval $(brew shellenv)
source /home/marlon/Git/zsh-snap/znap.zsh
znap source ohmyzsh/ohmyzsh plugins/gnu-utils
znap fpath _kubectl 'kubectl completion zsh'
EOF
env -i HOME=$PWD TERM=$TERM PATH=$PATH TERMINFO=$TERMINFO zsh -d 

/tmp/tmp.CzWxSd78rv/
% znap restart
Validating dotfiles...
Restarting Zsh...
%
```

**Comment by optix2000** [comment] 2022-01-05 00:30
```
% tmp=$(mktemp -d)
cd $tmp
git clone --depth 1 -- https://github.com/marlonrichert/zsh-snap.git
> .zshrc <<EOF
PS1='%# '
eval \$(brew shellenv)
source $tmp/zsh-snap/znap.zsh
znap source ohmyzsh/ohmyzsh plugins/gnu-utils
EOF
env -i HOME=$PWD PATH=$PATH TERM=$TERM zsh -d
Cloning into 'zsh-snap'...
remote: Enumerating objects: 46, done.
remote: Counting objects: 100% (46/46), done.
remote: Compressing objects: 100% (44/44), done.
remote: Total 46 (delta 0), reused 12 (delta 0), pack-reused 0
Receiving objects: 100% (46/46), 22.62 KiB | 7.54 MiB/s, done.
Cloning into 'ohmyzsh'...
remote: Enumerating objects: 1286, done.
remote: Counting objects: 100% (1286/1286), done.
remote: Compressing objects: 100% (1245/1245), done.
remote: Total 1286 (delta 22), reused 1058 (delta 21), pack-reused 0
Receiving objects: 100% (1286/1286), 1.07 MiB | 2.73 MiB/s, done.
Resolving deltas: 100% (22/22), done.
% echo "znap fpath _kubectl 'kubectl completion zsh'" >> .zshrc
% znap restart
Validating dotfiles...
Validation failed with exit status 1.
Restart aborted.
%
```

**Closed** 2022-01-11 14:55 UTC
Labels: question

**Comment by marlonrichert** [comment] 2022-01-11 14:58
Fixed! 

PS: If you enjoy using my software, please consider [sponsoring me](https://github.com/sponsors/marlonrichert). 🙂
