### ISSUE TITLE
znap.init command not found

### ISSUE THREAD

**Issue by AliTajelsir** [marlonrichert/zsh-snap#49] opened 2021-03-10 10:50 UTC
-  I'm getting the following error with the last commits in `termux`:
```
(anon):zf_mkdir:14: not enough arguments
..znap.init: command not found
```

- Untill commit e1e94b6 it was working fine.
- Zsh version `5.8-5`
- My `.zshrc`: [zshrc.txt](https://github.com/marlonrichert/zsh-snap/files/6115232/zshrc.txt)

**Comment by marlonrichert** [comment] 2021-03-10 14:51
```zsh
zstyle ':znap:*' git-dir $ZDOTDIR/znap
```
should be
```zsh
zstyle ':znap:*' plugins-dir $ZDOTDIR/znap
```

I thought about changing it at some point and apparently, I changed it in the Readme, but I never changed it in the code.

**Comment by marlonrichert** [comment] 2021-03-10 16:35
I cannot reproduce this. I tried your `.zshrc` file and it works fine for me.

What happens when you restart Zsh by doing `exec zsh -d`?

**Comment by AliTajelsir** [comment] 2021-03-10 22:31
> I cannot reproduce this. I tried your `.zshrc` file and it works fine for me.
> 
> What happens when you restart Zsh by doing `exec zsh -d`?

- This error happens for me only in `termux` but not `linux`

- I'll try after clearing the app data and will report back.

**Comment by marlonrichert** [comment] 2021-03-12 22:02
Should be fixed now on the `main` branch. Let me know if it isn't.

**Comment by AliTajelsir** [comment] 2021-03-13 07:14
> Should be fixed now on the `main` branch. Let me know if it isn't.

- Tried the latest commit just now, but it's still not working.
- Any log I can provide?

**Comment by marlonrichert** [comment] 2021-03-13 09:53
I pushed in some basic smoke testing with debug output. Please update and try again.

**Comment by AliTajelsir** [comment] 2021-03-13 13:44
- Tried the latest update, and it's working fine now.
- Thanks for your hard work!.

**Closed** 2021-03-14 12:42 UTC
Labels: bug
